language: generic
install:
    - pip3 install --user --upgrade pip
    - pip3 install --user --upgrade setuptools
    - pip3 install --user vim-vint
before_script:
    - uname -a
    - vim --version
script:
    - vint --warning $(git ls-files | grep -e '\.vim$' | grep -v vital) --color
    - vim -E -c 'set t_Co=256 rtp+=.' -c 'try | colorscheme spring-night | catch | cquit | endtry' -c 'quit'
    - ruby .ci/check_duplicate.rb
addons:
  apt:
    packages:
      - vim
      - python-dev
      - python3-dev
      - python3-pip
